//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IwwageNationalMIS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLevel
    {
        public int ID_PK { get; set; }
        public string UserLevelName { get; set; }
    }
}
